### ISSUE TITLE
No authentication support

### ISSUE THREAD

**Issue by mavit** [creaktive/LWP-Protocol-Net-Curl#12]
With `LWP::UserAgent`, you can call [`LWP::UserAgent::credentials()`](https://metacpan.org/pod/LWP::UserAgent#ua-credentials-netloc-realm) to get and set the username and password to use for a particular webpage or proxy.  This is ignored by `LWP::Protocol::Net::Curl::request()`.

Further, there doesn't appear to be a way when using `LWP::Protocol::Net::Curl` to access `Net::Curl::Easy::setopt()` to set these options manually.

**Comment by creaktive** [comment]
As I understand it, `credentials()` does not map very well to the _libcurl internals_. Is there any advantage when using `credentials()` as opposed to including `https://username:password@host...` in every URL?

**Comment by mavit** [comment]
Since this was three years ago I'm afraid I don't remember the details.  This was related to work for a previous client, so I can't look at the code to remind myself.

It could be that I was reporting this simply because `LWP::Protocol::Net::Curl` claims to be a drop-in replacement for `LWP`, but in this circumstance they are not compatible.

**Comment by creaktive** [comment]
I guess I was young and reckless when I claimed this ¯\\\_(ツ)_/¯ 
While using this very module, I proved myself multitude of times that it is indeed **not** a perfect replacement. Apologies for the misleading overconfidence :)
