### ISSUE TITLE
t/04-callback.t fails on CentOS 7

### ISSUE THREAD

**Issue by eserte** [creaktive/LWP-Protocol-Net-Curl#14]
On my CentOS 7 smoker I see the following failure with all perls installed here (the system one and various between 5.26.3 and 5.29.10):
```
#   Failed test 'received 1 chunks'
#   at t/04-callback.t line 31.
# Looks like you failed 1 test of 3.
t/04-callback.t .............. 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/3 subtests 
```
In case the libcurl version matters: the libcurl-7.29.0-51.el7.x86_64 rpm is installed here.

**Comment by creaktive** [comment]
Oooops I completely missed the fact that not every libcurl installation does support stuff that this test checks!
