### ISSUE TITLE
bad $response->base when redirect done

### ISSUE THREAD

**Issue by kni** [creaktive/LWP-Protocol-Net-Curl#17]
Hello.
You use $easy->setopt(CURLOPT_FOLLOWLOCATION,=> 1);
but LWP don't ready to get response with _previous requests.

For example. I have redirect:
> curl -s -D - http://localhost/rrr | grep Location
Location: http://localhost/ddd/1.html

Pure LWP return http://localhost/ddd/1.html as base url.
But when I use LWP::Protocol::Net::Curl I got http://localhost/rrr as base url.

When I disable CURLOPT_FOLLOWLOCATION, I got http://localhost/ddd/1.html.

Also I got good result if I comment https://metacpan.org/release/libwww-perl/source/lib/LWP/UserAgent.pm#L230.

Could you do parameter CURLOPT_FOLLOWLOCATION customizable? Let LWP process itself  the redirect .

**Comment by creaktive** [comment]
Hi! I think I remember this issue... If you set `$ua->requests_redirectable` to `[]`, LWP is going to handle the redirect instead of libcurl.

**Comment by kni** [comment]
No, if I set $ua->requests_redirectable to [] then LWP do not process redirect. And I got "302 Moved Temporarily" response.

**Comment by creaktive** [comment]
Aha... Another possibility is overriding per request, something like:
```perl
$ua->get(
    'http://localhost/rrr',
    X_CurlOpt_FollowLocation => 0,
);
```

**Comment by kni** [comment]
Thank you very much! I will use:
my $ua = LWP::UserAgent->new(default_headers => HTTP::Headers->new(X_CurlOpt_FollowLocation => 0));
I'm sorry my carelessness.
